# Generated by Django 6.0.7 on 2026-07-27 15:34

import contracts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitoDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=150, verbose_name='Nombre del Documento Requerido')),
                ('es_obligatorio', models.BooleanField(default=True, verbose_name='¿Es Obligatorio?')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Requisito Documental',
                'verbose_name_plural': 'Requisitos Documentales',
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Contrato',
                'verbose_name_plural': 'Tipos de Contratos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, unique=True, verbose_name='Número de Contrato')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa / Contratista')),
                ('nit', models.CharField(max_length=30, verbose_name='NIT / Identificación')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('POR_VENCER', 'Próximo a Vencer'), ('VENCIDO', 'Vencido'), ('RENOVADO', 'Renovado'), ('PENDIENTE_DOC', 'Pendiente por Documentación'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_a_cargo', to=settings.AUTH_USER_MODEL)),
                ('tipo_contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contracts.tipocontrato')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Creación de Contrato'), ('SUBIR_DOC', 'Subió Documento'), ('ELIMINAR_DOC', 'Eliminó Documento'), ('RENOVAR', 'Renovó Contrato'), ('ALERTA', 'Envío de Alerta Automática'), ('MODIFICAR', 'Modificación de Datos')], max_length=20)),
                ('descripcion', models.TextField(verbose_name='Descripción del cambio')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='contracts.contrato')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Auditoría',
                'verbose_name_plural': 'Historiales de Auditoría',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=200, verbose_name='Nombre del Archivo')),
                ('archivo', models.FileField(upload_to=contracts.models.ruta_documento_contrato, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'png', 'jpg', 'zip'])], verbose_name='Archivo Adjunto')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('es_version_actual', models.BooleanField(default=True, verbose_name='¿Es la versión actual?')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='contracts.contrato')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('requisito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.requisitodocumental')),
            ],
            options={
                'verbose_name': 'Documento de Contrato',
                'verbose_name_plural': 'Documentos de Contratos',
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='requisitodocumental',
            name='tipo_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='contracts.tipocontrato'),
        ),
        migrations.AlterUniqueTogether(
            name='requisitodocumental',
            unique_together={('tipo_contrato', 'nombre_documento')},
        ),
    ]
