# Generated by Django 6.0.7 on 2026-07-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='area_destino',
            field=models.CharField(default='General', max_length=150, verbose_name='Área de Destino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='correo_notificacion_opcional',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Opcional (Usuario/Responsable)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='correo_notificacion_principal',
            field=models.EmailField(default='General', max_length=254, verbose_name='Correo Principal (Admin @boccherini.com.co)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='tiempo_notificacion',
            field=models.IntegerField(choices=[(90, '90 días antes'), (30, '30 días antes'), (15, '15 días antes'), (5, '5 días antes')], default=30, verbose_name='Anticipación de Notificación'),
        ),
    ]
