# Generated by Django 6.0.7 on 2026-07-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contrato_area_destino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EMPRESA', 'Empresa'), ('PERSONA', 'Persona Natural')], default='EMPRESA', max_length=20)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('identificacion', models.CharField(max_length=30, unique=True, verbose_name='NIT / Documento')),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacto', models.CharField(blank=True, help_text='Persona de contacto (si aplica)', max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tercero',
                'verbose_name_plural': 'Terceros',
                'ordering': ['nombre'],
            },
        ),
    ]
