# Generated by Django 6.0.7 on 2026-07-29 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_tercero'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='tercero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='contracts.tercero', verbose_name='Tercero'),
        ),
    ]
