# Generated by Django 6.0.7 on 2026-07-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contrato_tercero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='correo_notificacion_opcional',
        ),
        migrations.AddField(
            model_name='contrato',
            name='correo_notificacion_secundario',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Secundario'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='correo_notificacion_principal',
            field=models.EmailField(max_length=254, verbose_name='Correo Principal'),
        ),
    ]
