# Generated by Django 6.0.7 on 2026-07-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_area_contrato_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tercero',
            name='activo',
        ),
        migrations.AddField(
            model_name='tercero',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tercero',
            name='cargo_contacto',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tercero',
            name='ciudad',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tercero',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='tipo',
            field=models.CharField(choices=[('PROVEEDOR', 'Proveedor'), ('CONTRATISTA', 'Contratista'), ('CLIENTE', 'Cliente'), ('PERSONA', 'Persona Natural'), ('EMPLEADO', 'Empleado'), ('ALIADO', 'Aliado Estratégico'), ('OTRO', 'Otro')], default='PROVEEDOR', max_length=20),
        ),
    ]
