# Generated by Django 6.0.7 on 2026-07-30 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_remove_tercero_activo_tercero_actualizado_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('nit', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('ciudad', models.CharField(blank=True, max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('pagina_web', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='tercero',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terceros', to='contracts.empresa'),
        ),
    ]
