# Generated by Django 6.0.7 on 2026-07-30 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_supervisor_contrato_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisores', to='contracts.empresa', verbose_name='Empresa'),
        ),
    ]
