# Generated by Django 6.0.7 on 2026-07-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_supervisor_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contratos/', verbose_name='Contrato PDF'),
        ),
    ]
