# Generated by Django 6.0.7 on 2026-08-04 14:24

import contracts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_contrato_archivo_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('obligatorio', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='documentocontrato',
            options={'ordering': ['tipo_documento'], 'verbose_name': 'Documento del Contrato', 'verbose_name_plural': 'Documentos de Contratos'},
        ),
        migrations.RenameField(
            model_name='documentocontrato',
            old_name='fecha_subida',
            new_name='fecha_carga',
        ),
        migrations.RemoveField(
            model_name='documentocontrato',
            name='es_version_actual',
        ),
        migrations.RemoveField(
            model_name='documentocontrato',
            name='nombre_archivo',
        ),
        migrations.RemoveField(
            model_name='documentocontrato',
            name='requisito',
        ),
        migrations.RemoveField(
            model_name='documentocontrato',
            name='subido_por',
        ),
        migrations.AddField(
            model_name='documentocontrato',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentocontrato',
            name='archivo',
            field=models.FileField(upload_to=contracts.models.ruta_documento_contrato),
        ),
        migrations.AlterField(
            model_name='documentocontrato',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='documentocontrato',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='contracts.tipodocumento'),
        ),
    ]
