# Generated by Django 6.0.7 on 2026-08-04 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_tipodocumento_alter_documentocontrato_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='area_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_destino', to='contracts.area', verbose_name='Área de Destino'),
        ),
    ]
