# Generated by Django 6.0.7 on 2026-08-04 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_alter_contrato_area_destino'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocontrato',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de contrato', 'verbose_name_plural': 'Tipos de contrato'},
        ),
        migrations.AlterField(
            model_name='tipocontrato',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tipocontrato',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipocontrato',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TipoContratoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatorio', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('tipo_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_requeridos', to='contracts.tipocontrato')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.tipodocumento')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.DeleteModel(
            name='RequisitoDocumental',
        ),
    ]
