# Generated by Django 6.0.7 on 2026-08-05 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_alter_tipocontrato_options_alter_tipocontrato_activo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoDocumento',
            new_name='TipoDocumentoContractual',
        ),
        migrations.AlterModelOptions(
            name='tipodocumentocontractual',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Documento Contractual', 'verbose_name_plural': 'Tipos de Documentos Contractuales'},
        ),
        migrations.AlterField(
            model_name='tipocontratodocumento',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_contrato', to='contracts.tipodocumentocontractual'),
        ),
    ]