# Generated by Django 6.0.7 on 2026-08-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_rename_tipodocumento_tipodocumentocontractual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodocumentocontractual',
            name='activo',
        ),
    ]
