# Generated by Django 6.0.7 on 2026-08-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_remove_tipodocumentocontractual_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tiempo_notificacion',
            field=models.IntegerField(choices=[(90, '90 días antes'), (30, '30 días antes'), (15, '15 días antes'), (5, '5 días antes'), (1, '1 día antes')], default=30, verbose_name='Anticipación de Notificación'),
        ),
    ]
