# Generated by Django 6.0.7 on 2026-08-19 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_alter_contrato_tiempo_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENCIMIENTO', 'Vencimiento contractual')], default='VENCIMIENTO', max_length=30)),
                ('dias_anticipacion', models.PositiveIntegerField(verbose_name='Días de anticipación')),
                ('fecha_programada', models.DateField(verbose_name='Fecha programada')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('enviada', models.BooleanField(default=False, verbose_name='Enviada')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('error_envio', models.TextField(blank=True, null=True, verbose_name='Error de envío')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='contracts.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Notificación de Contrato',
                'verbose_name_plural': 'Notificaciones de Contratos',
                'ordering': ['-creado_en'],
                'constraints': [models.UniqueConstraint(fields=('contrato', 'tipo', 'dias_anticipacion'), name='unique_alerta_contrato_anticipacion')],
            },
        ),
    ]
