# Generated by Django 6.0.7 on 2026-08-27 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0018_notificacioncontrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='contrato_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovaciones', to='contracts.contrato', verbose_name='Contrato anterior'),
        ),
    ]
